# Generated by Django 3.2.15 on 2022-11-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VkPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_vk', models.TextField(max_length=4096, verbose_name='Текст_поста')),
                ('photo_vk', models.URLField(max_length=4096, verbose_name='Фото_поста')),
            ],
        ),
    ]
