# Generated by Django 3.2.15 on 2022-08-23 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainanimals',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='mainanimals',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='animals.category'),
        ),
    ]
